/*USE Studentdb;
BEGIN TRANSACTION;
INSERT INTO Students (StudentID,Name,DateOfBirth)
VALUES (5,'TANVIR ALAM','2002-12-12');
COMMIT;
SELECT * FROM STUDENTS;*/
/*
BEGIN TRANSACTION;
UPDATE Students
SET Name ='Invalid'
WHERE StudentID ='3';
ROLLBACK;*/
--SELECT * FROM STUDENTS;
/*
BEGIN TRANSACTION;
INSERT INTO Students (StudentID,Name,DateOfBirth)
VALUES (6,'FARJANA RAHMAN','2002-03-20'); */
--SELECT * FROM STUDENTS;
/*
UPDATE Students
SET Name = 'F. Rahman '
WHERE StudentID = 6;
COMMIT; */
SELECT * FROM STUDENTS;